Collusic/collusic-new

- server/collusic-be/.gitignore
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CustomOAuth2UserService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/dto/GoogleTokenResponse.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/dto/NaverProfileResponse.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
* 클라이언트의 요청 정보를 바탕으로 회원가입 API를 구현함.
* 에러 핸들링과 Validation은 추후 구현 예정 (회원가입 실패 케이스들)
Close #154
> feat/154 : 회원가입 API 구현

- server/collusic-be/pom.xml
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/SwaggerConfig.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
- server/collusic-be/src/main/resources/application.properties
- swagger 적용 완료 (document 접근 url -> **{base_url}/swagger-ui/index.html**)
- 아직 validation 및 exception handling이 되어있지 않아서 status code가 ok만 이용되고 있습니다. 향후 프론트와 협의하여 상태 코드 정해야할 듯합니다.
Close #158
> faet/158: Swagger 적용 완료

- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRepository.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/NicknameValidationResponseDto.java
* 닉네임 중복 검사 API 구현
* 닉네임 중복 시 Exception을 보내면 좋을지 혹은 boolean으로 중복 여부를 구분할지. 만약 Exception을 보내는 것이 좋다면 추상화 레벨을 고려하여 재설계하여 반영할 예정
Close #168
> feat/168 - 닉네임 중복 검사 API 구현

- client/.gitignore
- client/src/App.tsx
- client/src/components/LoginButton.tsx
- client/src/components/Modal.tsx
- client/src/mocks/handlers/user.ts
- client/src/model/userModel.ts
- client/src/utils/axios.ts
- client/src/view/ProjectListView.tsx
- client/src/view/SignInView.tsx
- client/src/viewmodel/RedirectViewModel.tsx
- client/src/viewmodel/SignInViewModel.tsx
- client/src/viewmodel/SignUpViewModel.tsx
- 각 sns 로그인 타입에 따른 로그인 페이지로 리다이렉션
- redirect_url을 `localhost:3000/auth/redirect`로 설정
- loginType, refreshToken을 userModel에서 recoil atom으로 관리
- RedirectViewModel 에서 responseType에 따른 로그인 및 회원가입 로직 구현
- SIGN_UP 시 useNaviagte를 통해 SignUpViewModel로 회원정보 전달
- SignUpViewModel에서 useLocation을 통해 회원정보 수신
- userModel에서 recoil atom으로 관리하는 loginType이 RedirectViewModel에서 최신화되지 않아, /oauth2/login/${loginType}에서 loginType에 null값이 들어가 cors에러가 나타납니다.
- api 요청을 통해 전달받는 모든 key값은 camelCase를 적용
Close #{172}
> feat/172 구글 Oauth 로그인/회원가입 기능 구현 완료

- server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
* 소셜 로그인 응답 Dto 및 회원가입 응답 Dto 애트리뷰트들에 대한 카멜 케이스 적용
* 프론트엔드의 요청으로 내용 수정
Close #183
> refactor/183 : 응답 애트리뷰트에 대한 카멜케이스 적용

- server/collusic-be/src/main/java/com/collusic/collusicbe/service/TokenService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpResponseDto.java
* 리프레시 토큰을 HttpOnly 방식으로 쿠키에 담아 응답하기
https://dncjf64.tistory.com/292
Close #199
> Refactor/199 : 리프레시 토큰 응답 방식 개선하기

- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/NicknameValidationResponseDto.java
* 닉네임 중복 체크 API 성공 / 실패 응답에 status와 message를 활용할 수 있도록 한다.
* 프론트엔드와 상의 후 API 개선하기
Close #197
> Refactor/197 : 닉네임 중복 체크 기능 응답 구조 수정

- server/collusic-be/src/main/java/com/collusic/collusicbe/service/MemberService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/S3Service.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProfileUploadResponseDto.java
- cloudfront에 원본 s3 버킷과 리사이징 s3 버킷 둘다 적용되도록 설정
- api 응답 바디에 원본 이미지 url과 리사이징 이미지 url 담기도록 변경
- api 요청할 때마다 기존 사용자 프로필 이미지 버킷에서 덮어쓰도록 변경
빠른 시간 안에 해결해 다음 스프린트에 지장없이 진행할 수 있다면 아래 사항들을 추가적으로 고민하고 반영하고자 합니다.
- 기존 이미지를 덮어쓰는 것이 아닌 제거하도록 변경. 파일명은 {nickname}_{타임스탬프}.png가 될 수 있도록
- 기존 이미지 url 추가 및 default 적용
- 기존 이미지로 초기화 api 구현
- member 테이블에 resized profile url 컬럼을 추가할 것인지 논의 후 반영
- rest 관점에서 post에서 url을 응답하는게 맞을지 논의 후 반영
Close #208
> [Refactor/208]: 프로필 이미지 업로드 api 변경사항 반영

- client/.eslintrc.js
- client/src/components/atoms/Button/index.tsx
- client/src/components/atoms/LoginButton/index.tsx
- client/src/components/atoms/RecordButton/index.tsx
- client/src/components/atoms/Toggle/index.tsx
- client/src/components/blocks/Bpm/index.tsx
- client/src/components/blocks/Bpm/style.scss
- client/src/components/blocks/RecordDevice/index.tsx
- client/src/components/blocks/SessionMelody/index.tsx
- client/src/stories/Bpm.stories.tsx
- client/src/stories/RecordButton.stories.tsx
- client/src/stories/RecordDevice.stories.tsx
- client/src/utils/slider.ts
- client/src/viewmodel/ProjectViewModel.tsx
- projectModel의 bpmState를 통해 bpm slider를 구현하였습니다.
- getSliderHandlePosition 로직을 수정하였습니다.(추가)
- bpm 모든 컴포넌트의 위치를 absolute로 수정하였습니다.(추가)
- 뷰 로직에서 현재 bpm의 상태를, viewmodel에서 bpm의 전역적 상태를 관리하도록 리팩토링하였습니다.(추가)
- 현재 bpm의 현황에 따라 진행바가 하얀색으로 칠해집니다.(추가)
- getSliderHandlePosition util 함수를 통해 sliderHandle 컴포넌트 위에 현재 bpm 상태를 보여줍니다.
- 현재 sliderHandle 위에서 현재 bpm에 대해 span 태그로 보여주는데 bpm이 보이는 부분은 클릭이 되질 않습니다.
- 현재 bpm의 현황을 진행 바의 하얀색 바를 통해 보여주는데 해당 영역이 클릭되지 않습니다.
- getBoundingClientRect()를 통해 ref로 추적한 컴포넌트의 스타일을 가져올 수 있습니다.
Close #221
> feature/221: BPM 컴포넌트 구현 완료

- server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JwtAuthenticationEntryPoint.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Member.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Project.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectRepository.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Measure.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/TrackRepository.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/TrackTag.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/ForbiddenException.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/UnAuthorizedException.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/advice/ExceptionControllerAdvice.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/TrackService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/ProjectController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TrackController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ProjectResponseDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateRequestDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackCreateResponseDto.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/TrackUpdateRequestDto.java
- server/collusic-be/src/main/resources/application.yml
- server/collusic-be/src/main/resources/import.sql
- server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/AbstractAcceptanceTest.java
- server/collusic-be/src/test/java/com/collusic/collusicbe/acceptanceTest/TrackAcceptanceTest.java
- server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
트랙 API 구현
- 트랙 생성 : `POST /projects/{projectId}/tracks`
- 트랙 수정 : `PUT /projects/{projectId}/tracks/{trackId}`
- 트랙 삭제 : `DELETE /projects/{projectId}/tracks/{trackId}`
- 개별 트랙에 대한 조회 api는 필요한 시점에 추가 개발하는 것으로 하였습니다.
- Track이 Project 도메인과 밀접한 연관이 있어 Project에 대한 일부 기능을 임시 구현했습니다. 작업하실 때 이어서 구현해주세요
Close #229
> Feat/229: 트랙 CRUD API 구현 완료

- server/collusic-be/src/test/java/com/collusic/collusicbe/domain/track/TrackServiceTest.java
- 트랙 생성자가 본인이 아닌 트랙을 삭제하려는 경우 Forbidden exception을 던져야하는데 Illegal state exception을 던지도록 테스팅을 하고 있었음
- 기대 예외를 IllegalStateException에서 ForbiddenException으로 변경하여 해결하였음
Close #232
> Fix/232: 애플리케이션 빌드 시 트랙 관련 테스트 실패하는 이슈 해결

- server/collusic-be/Dockerfile-dev
- server/collusic-be/docker-compose.yml
- server/collusic-be/run_script.sh
- 배포 및 테스트 서버 구동을 위한 도커 파일 및 설정을 추가하였습니다.
- 향후 배포 시에도 실행 환경 격리를 위해 도커를 이용한 배포를 할 것 같아서 메인 브랜치에 머지해도 될 것 같아 pr 날립니다.
Close #231
> Feat/231: 배포 및 테스트 서버를 위한 도커 설정 완료

- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/advice/ExceptionControllerAdvice.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/jwt/TokenNotFoundException.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
* 리프레시 토큰을 통한 액세스 토큰 재발급 API 추가
* 새로고침 시 로그인 상태 유지를 위해 (프론트엔드 요청)
Close #243
> Feat/243 : 액세스 토큰 재발급 API

- server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationProvider.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/global/exception/jwt/ExpiredTokenException.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/service/TokenService.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/TokenController.java
- server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/ReissuedTokenDto.java
* 토큰 재발급 API 수정
* 액세스 토큰 만료 상황에서 리프레시 토큰을 통한 액세스 토큰 재발급
* 리프레시 토큰 만료 상황에서 세션 무효화, 쿠키 제거, SecurityContext 비우기
* io.jsonwebtoken.ExpiredJwtException과 커스텀 Exception의 네임이 같은 문제로 디버거가 네임 구별을 못하는 문제 발생하여 이를 해결했습니다.
Close #246
> Fix/246 : CORS 문제 해결(토큰 재발급 필터 수정)

- server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
* SpringSecurityConfig logout disable
*  SpringSecurityConfig logout disable을 하지 않을 경우 시큐리티 내부에서 http://localhost:8080/login?logout 으로 리다이렉트 처리하는 것으로 보입니다.
Close #253
> fix : 로그아웃 기능 버그 해결

- client/.eslintrc.js
- client/src/App.tsx
- client/src/components/blocks/PlayStick/index.tsx
- client/src/components/blocks/PlayStick/style.scss
- client/src/components/blocks/ProjectSetting/index.tsx
- client/src/components/blocks/ProjectSetting/style.scss
- client/src/components/blocks/TrackSpace/index.tsx
- client/src/components/blocks/TrackSpace/style.scss
- client/src/stories/PlayStick.stories.tsx
- client/src/stories/TrackSpace.stories.tsx
- client/src/viewmodel/ProjectItemViewModel.tsx
- client/src/viewmodel/ProjectSettingViewModel.tsx
- 재생 막대 바
- ProjectSettingViewModel 라우터 설정
- 재생 막대 바의 props로 time, setTime 전달
- dragEvent를 통해 재생 막대 바 이동 및 setTime 업데이트
- 프로젝트 상세페이지의 경우, 프로젝트가 10개가 모두 차있지 않은 상황에 한해서 프로젝트를 수정할 수 있으므로 프로젝트 상세페이지와 수정페이지 모두 ProjectSettingViewModel을 프로젝트 상세에서 사용
- 현재 재생 시간을 나타내는 time, setTime을 ProjectSettingViewModel에 생성 후, 자식 컴포넌트에 props로 전달
- 오늘 구현한 트랙박스 ProjectSettingViewModel에 삽입 후 scss 수정 필요
Close #300
> feat/300: 재생 막대 바 및 트랙 편집 영역 구현

- client/public/index.html
- client/src/components/blocks/NavBar/style.scss
해상도가 줄어들면 배너와 텍스트가 깨지는 현상 해결
Close #358
> qa/358: 해상도가 줄어들면 배너와 텍스트가 깨지는 현상 해결

- client/src/components/atoms/TrackIcon/index.tsx
- client/src/components/atoms/TrackIcon/style.scss
- client/src/components/blocks/ProjectItem/style.scss
트랙 아이콘 목록이 프로젝트 컴포넌트 밖으로 오버되는 현상 해결
Close #356
> fix/356: 트랙 아이콘 목록이 프로젝트 컴포넌트 밖으로 오버되는 현상 해결

- client/src/components/blocks/BpmBar/style.scss
- client/src/components/blocks/RecordDevice/style.scss
> Fix/395: [QA] 입력장치 열었을 때 프로젝트 세팅 박스 레이아웃이 깨지는 현상 해결

- client/src/components/atoms/TrackPlayBox/index.tsx
- client/src/components/atoms/TrackRecordBox/index.tsx
- client/src/components/atoms/TrackRecordBox/style.scss
- client/src/components/blocks/TrackPlayer/index.tsx
- client/src/components/blocks/TrackSetting/index.tsx
- client/src/hooks/useCreateTrack.ts
- client/src/hooks/useTrackPlayer.ts
- client/src/viewmodel/UnderPlayBarViewModel.tsx
- 녹음이 시작되면 TrackPlayer의 시간과 재생 상태를 조작할 수 없도록 수정했어요.
- Close #403
> Feat/403: [FE] [녹음] 녹음 시 트랙 재생 관련 인터랙션 막기

- client/src/components/blocks/ProjectSetting/index.tsx
- client/src/hooks/useCreateTrack.ts
- client/src/hooks/useRecord.ts
- client/src/hooks/useTrackPlayer.ts
- 녹음 중단 시 `interrupted` flag 전달
- 녹음 중이거나 트랙이 있는 경우에만 재생
- 트랙이 변경되면(녹음된 트랙이 제거되면) 트랙 재생 멈춤, 재생 시간 0으로 초기화
- 프로젝트 생성 페이지에서도 녹음 시작 시 하단 재생바의 재생 버튼이 비활성화되어야하므로 `isRecording` props 전달
- 브랜치를 Fix로 만들었어야하는데 Feat으로 만들었어요.. 죄송합니당 😅
- Close #390
> Fix/390: [FE] [녹음] 녹음을 중단하면 녹음이 저장되지 않고 바로 삭제될 수 있도록 수정
