server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
- 요청자 등록 api 수정
- 요청 데이터를 받는 핸들러 매핑의 파라미터 Dto 안에 Dto 객체를 한번 더 Wrapping 시킴으로써의 오류 발생
- 컨트롤러에서의 핸들러 매핑 수정
=> [Fix] Feat/be/Issue-3

client/src/App.tsx, client/src/view/CreateRequestPageView.tsx
- CreateRequestPageView 컴포넌트 생성
- App.tsx에서 /createrequest 라우터 설정
=> feat : 요청작생성페이지 생성

server/collusic-be/src/main/java/com/collusic/collusicbe/domain/contributeproject/ContributeProjectRepository.java, server/collusic-be/src/main/java/com/collusic/collusicbe/service/RequestProjectService.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
=> feat : 요청작 삭제 API 수정

server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/RequestProjectApiController.java
=> [Refactor] 메인페이지 요청작 페이지네이션 기능 정렬 기준 정의

client/src/utils/axios.ts, client/src/viewmodel/CreateRequestViewModel.tsx
- form button 클릭 시 /api/requestprojects로 post
- axios에 TEST_API 추가
=> [Feature] Feat/fe/Issue-53 post 요청 기능 구현

client/src/view/FloatingReqCreateButtonView.tsx, client/src/view/NavBarView.tsx
- #107 
- 헤더 로고, create project 버튼 링크 연결
=> [Feature] 헤더 로고, create project 버튼 링크 연결

.github/ISSUE_TEMPLATE/feature_request.md
- Feature request : feature에 해당하는 이슈 템플릿
- bug report : bug 관련 이슈 템플릿
- refactor request : 리팩토링 관련 이슈 템플릿
close #127
=> setting: issue templates

server/collusic-be/pom.xml, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Member.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/MemberRole.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/Role.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/member/SnsType.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Contribute.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Likes.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/Project.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/session/Session.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Measure.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/Track.java, server/collusic-be/src/main/java/com/collusic/collusicbe/domain/track/TrackTag.java
* Member 엔티티 클래스 추가하기
* MemberRole 엔티티 클래스 추가하기
* Role 엔티티 클래스 추가하기
* Project 엔티티 클래스 추가하기
* Contribute 엔티티 클래스 추가하기
* Likes 엔티티 클래스 추가하기
* Track 엔티티 클래스 추가하기
* Session 엔티티 클래스 추가하기
* TrackTag Enum 클래스 추가하기
* SnsType Enum 클래스 추가하기
* Measure Enum 클래스 추가하기
Close #128
=> Feat/be/issue 128 : Entity class 추가

server/collusic-be/pom.xml, server/collusic-be/src/main/java/com/collusic/collusicbe/util/JWTUtil.java, server/collusic-be/src/test/java/com/collusic/collusicbe/util/JWTUtilTest.java
* accessToken 발급 기능
* refreshToken 발급 기능
* 토큰 유효성 검증 기능
* 각 기능에 대한 테스트 코드 작성
* 토큰 검증에 대한 예외 처리
* 검증에 사용되는 SECRET KEY 코드에서 감추기
* 토큰 검증 결과 객체에 대해 생각해보기
Close #142
=> feat/142 - JWT Util 클래스 구현

client/src/utils/style/Modal.scss, client/src/view/ModalView.tsx
모달창 내 닫기 버튼의 class 선택자로 css 적용되도록 수정했습니다.
padding, height 속성 값도 적절히 변경했습니다.
Close #164
=> bug/164: 회원가입/로그인 모달창 css 수정 완료

server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/dto/GoogleProfileResponse.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/dto/KakaoProfileResponse.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/dto/NaverProfileResponse.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
* OAuth2 리소스 서버로부터 profile url을 추가로 받아온다.
Close #169
=> feat/169 : OAuth2 리소스 서버로부터 profile url 추가로 받아오는 기능 구현

server/collusic-be/src/main/java/com/collusic/collusicbe/config/SecurityConfig.java
- CORS 이슈 해결
- Spring Security Cofig에 CORS 설정 코드 추가
- OPTIONS는 Security filter가 ingnore되도록 설정
- 현재는 Allow Origin 리스트를 하드코딩하였지만, 추후 더 효과적으로 관리할 수 있도록 수정할 필요가 있을 것 같습니다.
Close #186
=> Bug/186: CORS 이슈 해결

server/collusic-be/pom.xml, server/collusic-be/src/main/java/com/collusic/collusicbe/config/S3Config.java, server/collusic-be/src/main/resources/application-aws.yml
- 이미지 파일 업로드를 위한 s3 및 cloudfront 적용
Close #188
=> feat/188 : s3 및 cloudfront 적용 완료

.gitignore, client/src/App.tsx, client/src/utils/axios.ts, client/src/utils/validation.tsx, client/src/viewmodel/RedirectViewModel.tsx, client/src/viewmodel/SignInViewModel.tsx, client/src/viewmodel/SignUpViewModel.tsx
닉네임에 영어, 한글, 숫자 외 특수문자, 공백, 이모지 등이 포함되는 경우`alert`창이 뜨도록 작업 완료했습니다.
추후 이슈 따로 만들어서 수아님이 디자인해주신 경고창이 뜨도록 수정하곘습니다!
Close #190
=> feat/190: 회원가입 시 닉네임 유효성 검사 작업 완료

server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/dto/SignUpRequestDto.java
* 닉네임 사이즈 검증 예외 메시지 수정
Close #203
=> Fix/203 : 닉네임 사이즈 검증 예외 메시지 수정

client/src/components/atoms/Button/index.tsx, client/src/components/atoms/LoginButton/index.tsx, client/src/components/blocks/SignIn/index.tsx, client/src/components/blocks/TrackTag/index.tsx, client/src/stories/TrackTag.stories.tsx, client/src/viewmodel/SignInViewModel.tsx
컴포넌트의 handler props와 handler 함수의 이름을 일치시킵니다.
Close #237
=> Fix/237: handle 함수 props 이름 변경 완료

server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2LoginResponseDto.java
* 리프레시 토큰을 쿠키를 통해 응답하도록 기존 바디 응답에서 제거
Close #240
=> Fix/240 : 회원가입 상황시 응답 바디에서 리프레시 토큰 제거

server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/CorsFilter.java, server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/ExceptionHandlerFilter.java, server/collusic-be/src/main/java/com/collusic/collusicbe/config/auth/JWTAuthenticationFilter.java, server/collusic-be/src/main/java/com/collusic/collusicbe/util/CookieUtils.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/controller/MemberController.java
* 로그아웃 기능 추가
* 컨트롤러를 거치지 않고 Filter 레벨에서 응답 반환 시 CORS와 관련된 응답이 헤더에 포함되지 않아 CORS 문제 발생 -> CORS 필터 추가로 해결
* 쿠키 관련 메서드 유틸 클래스로 분리
Close #249
=> Feat/249 : 로그아웃 기능 추가 및 CORS 필터 추가 

server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java
* 소셜 로그인 시 리프레시 토큰 쿠키에 담아서 응답 보내기
Close #251
=> fix/251 : 로그인 시 리프레시 토큰 쿠키에 담기

client/.eslintrc.js, client/package-lock.json, client/src/viewmodel/AuthVerify.tsx
- AuthVerify가 불필요한 root에서는 수행하지 않도록 수정
- 추후 프로젝트 상세 페이지도 url 확정 후 추가하도록 하겠습니다.
Close #269
=> feat/269: AuthVerify를 필요한 location에서만 하도록 수정 완료

server/collusic-be/src/main/java/com/collusic/collusicbe/domain/project/ProjectRepository.java, server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java, server/collusic-be/src/test/java/com/collusic/collusicbe/domain/project/ProjectServiceTest.java
* 프로젝트 도메인 테스트 커버리지 높이기 위한 인수테스트 및 단위 테스트 추가
Close #274
=> Feat/274 : 프로젝트 도메인 테스트 커버리지 높이기

server/collusic-be/src/main/java/com/collusic/collusicbe/service/ProjectService.java, server/collusic-be/src/main/resources/import.sql
미디어 파일 url 더미데이터에 추가하였습니다. 임시로 두 가지 음원 url을 번갈아가며 넣어두었습니다.
Close #317
=> Chore/317: 미디어 파일 url 더미데이터에 추가 완료

client/src/App.tsx, client/src/components/atoms/LikeButton/index.tsx, client/src/components/atoms/PreviewButton/index.tsx, client/src/components/blocks/ProjectItem/style.scss, client/src/types/projectType.ts, client/src/viewmodel/AuthVerify.tsx, client/src/viewmodel/ProjectItemViewModel.tsx
미리듣기 클릭 및 좋아요 클릭 시 바로 상세페이지로 이동하는 현상 해결
Close #323
=> Fix/323: 미리듣기 클릭 및 좋아요 클릭 시 바로 상세페이지로 이동하는 현상 해결

client/src/components/atoms/Bpm/index.tsx, client/src/components/atoms/Bpm/style.scss, client/src/components/blocks/BpmBar/index.tsx, client/src/components/blocks/BpmBar/style.scss, client/src/components/blocks/ProjectSetting/index.tsx, client/src/stories/Bpm.stories.tsx, client/src/stories/BpmBar.stories.tsx
=> Feat/282: 상세페이지 Bpm 컴포넌트 구현

client/src/components/atoms/DetailTitle/index.tsx, client/src/components/atoms/DetailTitle/style.scss, client/src/stories/DetailTitle.stories.tsx
상세페이지 프로젝트 제목 컴포넌트 구현
Close #280
=> Feat/280: 상세페이지 프로젝트 제목 컴포넌트 구현

client/src/components/atoms/LikeButton/index.tsx, client/src/components/atoms/LikeButton/style.scss, client/src/stories/LikeButton.stories.tsx
=> Feat/281: 좋아요 버튼 구현

client/src/components/atoms/LikeButton/index.tsx, client/src/components/atoms/LikeButton/style.scss, client/src/components/atoms/PlayButton/style.scss, client/src/components/atoms/TrackIcon/style.scss, client/src/components/blocks/ProjectItem/index.tsx, client/src/components/blocks/ProjectItem/style.scss, client/src/components/blocks/ProjectList/style.scss, client/src/components/pages/ProjectListPage/style.scss
프로젝트 목록이 가운데 정렬되는 현상 해결
Close #357
=> Feat/qa/357: 프로젝트 목록이 가운데 정렬되는 현상 해결

server/collusic-be/src/main/java/com/collusic/collusicbe/config/WebConfig.java, server/collusic-be/src/main/java/com/collusic/collusicbe/global/auth/CorsFilter.java
=> setting: cors 설정 추가(collusic.com)

client/src/viewmodel/SignInViewModel.tsx
oauth 로그인 시 localhost로 리다이렉션되는 현상 해결
Close #367
=> fix: oauth 로그인 시 localhost로 리다이렉션되는 현상 해결

client/src/viewmodel/SignInViewModel.tsx
- window.location.href -> window.location.origin 으로 수정
- Close #373
=> fix/373: OAuth redirect uri 수정

client/package.json, client/src/App.tsx, client/src/api/axios.ts, client/src/api/project.ts, client/src/components/atoms/Auth/hooks/useAuth.ts, client/src/components/atoms/RecordButton/index.tsx, client/src/components/atoms/Span/style.scss, client/src/components/atoms/TrackPlayBox/index.tsx, client/src/components/atoms/TrackRecordBox/index.tsx, client/src/components/blocks/BpmBar/index.tsx, client/src/components/blocks/ProjectSetting/index.tsx, client/src/components/blocks/RecordDevice/index.tsx, client/src/components/blocks/SoundBar/index.tsx, client/src/components/blocks/TrackPlayer/index.tsx, client/src/components/blocks/TrackSetting/index.tsx, client/src/components/blocks/TrackSetting/style.scss, client/src/components/blocks/TrackSpace/index.tsx, client/src/components/blocks/UnderPlayBar/index.tsx, client/src/hooks/useAudios.ts, client/src/hooks/useTime.ts, client/src/hooks/useTrackSetting.ts, client/src/model/authModel.ts, client/src/model/projectModel.ts, client/src/model/signInModel.ts, client/src/types/projectType.ts, client/src/types/trackType.ts, client/src/viewmodel/CreateTrackViewModel.tsx, client/src/viewmodel/ProjectItemViewModel.tsx, client/src/viewmodel/ProjectSettingViewModel.tsx
- 트랙 재생에 필요한 전반적인 기능을 구현했습니다.
- 작업 내용 간단히 코멘트로 남기겠습니다!
- Close #295
- Close #296
- Close #297 
- Close #298 
- Close #303
=> feat/303: 트랙 재생 영역 viewmodel 구현

client/package-lock.json, client/package.json, client/src/index.tsx
- typescript 4.8.5 적용 (1년 안에 가장 많은 다운로드 수)
- react-dom 버전 변경으로 인한 렌더 구현 변경
- msw script 적용으로 warning 해결
- `npm run mock` 으로 실행하시면 msw가 실행됩니다.
Close #381
=> Feat/381: 마이그레이션 에러 수정

client/src/components/blocks/ProjectSetting/index.tsx, client/src/components/blocks/TrackSetting/index.tsx, client/src/hooks/useCreateTrack.ts
- 프로젝트 생성 페이지에서 트랙 녹음 기능을 구현했어요.
- 트랙 생성 로직을 트랙 생성페이지와 프로젝트 생성페이지에서 재사용하기 위해 `useCreateTrack` hook으로 추출했어요.
- Close #386
=> Feat/386: [프로젝트 생성] 트랙 녹음 기능 구현 완료

server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2ClientService.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/OAuth2Controller.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/google/GoogleClientService.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/kakao/KakaoClientService.java, server/collusic-be/src/main/java/com/collusic/collusicbe/web/auth/naver/NaverClientService.java, server/collusic-be/src/main/resources/application-dev_oauth.yml, server/collusic-be/src/main/resources/application-prod_oauth.yml, server/collusic-be/src/main/resources/application-prod_redis.yml
=> Fix : Oauth 버그 수정

client/src/components/blocks/RecordDevice/index.tsx, client/src/hooks/useInputDevice.ts
- 프로젝트 추가, 프로젝트 수정, 트랙 추가 페이지에 집근했을 때 오디오 입력장치 권한이 비허용 상태인 경우, 권한 요청
- 초기에 사용 중인 입력장치를 노출
Close #389
=> feat/389:  현재 사용 중인 입력장치 노출

client/src/components/atoms/Auth/hooks/useAuth.ts, client/src/model/authModel.ts, client/src/viewmodel/ProjectItemViewModel.tsx
=> Fix/391 : [QA] [로그인] 로그인이 간헐적으로 풀리는 현상

client/src/api/axios.ts, client/src/components/atoms/Auth/AuthRequired.tsx, client/src/viewmodel/RouteHandlerViewModel.tsx
- needToLogin query string을 통해 모달이 열리도록 구현하였습니다.
Close #401
=> feat/401 : statusCode가 401일 때, 메인 페이지 리다이렉션 및 로그인 모달 노출 구현

client/src/api/axios.ts, client/src/components/atoms/Auth/hooks/useAuth.ts, client/src/mocks/handlers/user.ts, client/src/model/authModel.ts, client/src/viewmodel/RouteHandlerViewModel.tsx
=> Feat/409: [FE] 토큰 재발급 및 로그아웃 api 도메인 에러

client/src/api/axios.ts, client/src/api/project.ts, client/src/components/atoms/TrackPlayBox/index.tsx, client/src/components/blocks/ProjectSetting/index.tsx, client/src/components/blocks/TrackPlayer/index.tsx, client/src/constants/key.ts, client/src/hooks/useAudios.ts, client/src/types/audioType.ts, client/src/utils/audio.ts, client/src/viewmodel/CreateProjectViewModel.tsx
- 기존 timeout 3000 → 5000 으로 수정했어요. (느린 네트워크 환경(ex. 핫스팟)에서 timeout이 계속 발생해요..🥲)
- 불필요한 axios custom header을 제거했어요.
- 새롭게 녹음된 트랙에 `new`라는 매직 리터럴 id를 사용하고 있었는데, 이를 `NEW_TRACK_ID` 값으로 상수화했어요.
- 아래 타입의 formData를 body에 실어 `/projects` api로 post 요청을 보내도록 구현했어요.
- Close #411
=> Fix/411: [FE] [프로젝트 생성] 프로젝트 생성 api 요청에 오디오 파일 추가

client/src/components/atoms/TrackPlayBox/index.tsx, client/src/components/atoms/TrackPlayBox/style.scss, client/src/components/blocks/TrackPlayer/index.tsx, client/src/components/blocks/TrackSetting/index.tsx, client/src/components/blocks/TrackSpace/index.tsx
- 트랙 위에 사용자 프로필, 트랙 정보를 보여주는 UI를 구현했어요.
- Close #406
=> Feat/406: [FE] [트랙 추가] 트랙에 사용자 프로필, 트랙 정보 UI 추가
